# Generated by Django 4.2.5 on 2023-11-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_is_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_discount',
        ),
    ]
